/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface YooSpinner {}
  interface YooSpinnerAttributes extends StencilHTMLAttributes {}

  interface YooStockFinder {}
  interface YooStockFinderAttributes extends StencilHTMLAttributes {
    'onYooSymbolSelected'?: (event: CustomEvent<string>) => void;
  }

  interface YooStockPrice {
    'stockSymbol': string;
  }
  interface YooStockPriceAttributes extends StencilHTMLAttributes {
    'stockSymbol'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'YooSpinner': Components.YooSpinner;
    'YooStockFinder': Components.YooStockFinder;
    'YooStockPrice': Components.YooStockPrice;
  }

  interface StencilIntrinsicElements {
    'yoo-spinner': Components.YooSpinnerAttributes;
    'yoo-stock-finder': Components.YooStockFinderAttributes;
    'yoo-stock-price': Components.YooStockPriceAttributes;
  }


  interface HTMLYooSpinnerElement extends Components.YooSpinner, HTMLStencilElement {}
  var HTMLYooSpinnerElement: {
    prototype: HTMLYooSpinnerElement;
    new (): HTMLYooSpinnerElement;
  };

  interface HTMLYooStockFinderElement extends Components.YooStockFinder, HTMLStencilElement {}
  var HTMLYooStockFinderElement: {
    prototype: HTMLYooStockFinderElement;
    new (): HTMLYooStockFinderElement;
  };

  interface HTMLYooStockPriceElement extends Components.YooStockPrice, HTMLStencilElement {}
  var HTMLYooStockPriceElement: {
    prototype: HTMLYooStockPriceElement;
    new (): HTMLYooStockPriceElement;
  };

  interface HTMLElementTagNameMap {
    'yoo-spinner': HTMLYooSpinnerElement
    'yoo-stock-finder': HTMLYooStockFinderElement
    'yoo-stock-price': HTMLYooStockPriceElement
  }

  interface ElementTagNameMap {
    'yoo-spinner': HTMLYooSpinnerElement;
    'yoo-stock-finder': HTMLYooStockFinderElement;
    'yoo-stock-price': HTMLYooStockPriceElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
